import acm.graphics.GImage;
import acm.graphics.GLabel;
import acm.graphics.GOval;
import acm.graphics.GRect;
import acm.util.RandomGenerator;

public class BreakoutVars {
    public static GLabel peremogaOr3rada;
    public static GLabel numberOfPoints;
    public static int pointsCheck;
    public static GImage points;
    public static double vx;
    public static double vy;
    public static final int APPLICATION_WIDTH = 800;
    public static final int APPLICATION_HEIGHT = 1000;
    public static GOval ball;
    public static GRect brick;
    public static GLabel numberOfHearts;
    public static int gameStatus = 0;
    public static final int WIDTH_OFFSET = 22;
    public static final int HEIGHT_OFFSET = 86;
    public static final int WIDTH_ = APPLICATION_WIDTH + WIDTH_OFFSET;
    public static final int HEIGHT_ = APPLICATION_HEIGHT + HEIGHT_OFFSET;
    public static GImage hearts;
    public static final int PADDLE_WIDTH = 160;
    public static final int PADDLE_HEIGHT = 30;
    public static final int PADDLE_Y_OFFSET = 150;
    public static final int NBRICKS_PER_ROW = 6;
    public static final int NBRICK_ROWS = 6;
    public static final int BRICK_SEP = 14;
    public static final int BRICK_WIDTH = (APPLICATION_WIDTH - (NBRICKS_PER_ROW + 1) * BRICK_SEP) / NBRICKS_PER_ROW;
    public static GRect levelButton1;
    public static GRect levelButton2;
    public static GRect levelButton3;
    public static final double BUTTON_WIDTH = 200.0;
    public static final double BUTTON_HEIGHT = 60.0;
    public static final double BUTTON_SPACING = 20.0;
    public static final double BUTTON_Y_OFFSET = 400;
    public static RandomGenerator rgen = RandomGenerator.getInstance();
    public static GRect paddle;
    public static boolean isMousePressed = false;
    public static final int BRICK_HEIGHT = 15;
    public static int heartsCheck = 3;
    public static final int BALL_RADIUS = 30;
    public static final int BRICK_Y_OFFSET = 80;
    public static int numberOfBricks = NBRICK_ROWS * NBRICKS_PER_ROW;
    public static int numberOfRemovedBricks = 0;
    public static final int NTURNS = 3;
    public static GLabel level1;
    public static GLabel level2;
    public static GLabel level3;
}
